import type { Product } from "@curtiz/domain";

export const demoProducts: Product[] = [
  {
    id: "wave-preto",
    slug: "flip-flop-wave-preto",
    name: "curti Z Flip-Flop Wave Preto",
    category: "Masculino",
    description: "Leve, resistente e macio para acompanhar todos os momentos.",
    priceInCents: 5990,
    compareAtPriceInCents: 7990,
    rating: 4.9,
    reviews: 1234,
    colors: ["Preto", "Marinho"],
    sizes: ["37/38", "39/40", "41/42", "43/44"],
    image: "/images/products/wave-preto.webp",
    featured: true,
    stock: 156
  },
  {
    id: "slim-coral",
    slug: "flip-flop-slim-coral",
    name: "curti Z Flip-Flop Slim Coral",
    category: "Feminino",
    description: "Design minimalista em tom coral vibrante e palmilha confortável.",
    priceInCents: 5490,
    compareAtPriceInCents: 6990,
    rating: 4.8,
    reviews: 982,
    colors: ["Coral", "Rosa"],
    sizes: ["33/34", "35/36", "37/38", "39/40"],
    image: "/images/products/slim-coral.webp",
    featured: true,
    stock: 73
  },
  {
    id: "bold-marinho",
    slug: "slide-bold-marinho",
    name: "curti Z Slide Bold Marinho",
    category: "Slides",
    description: "Slide marcante com tira acolchoada e base anatômica.",
    priceInCents: 7990,
    compareAtPriceInCents: 9990,
    rating: 4.7,
    reviews: 756,
    colors: ["Marinho", "Branco"],
    sizes: ["35/36", "37/38", "39/40", "41/42"],
    image: "/images/products/bold-marinho.webp",
    featured: true,
    stock: 98
  },
  {
    id: "comfort-areia",
    slug: "sandalia-comfort-areia",
    name: "curti Z Sandália Comfort Areia",
    category: "Sandálias",
    description: "Sandália versátil com ajuste seguro e acabamento suave.",
    priceInCents: 7990,
    compareAtPriceInCents: 10990,
    rating: 4.8,
    reviews: 643,
    colors: ["Areia", "Caramelo"],
    sizes: ["34", "35", "36", "37", "38", "39"],
    image: "/images/products/comfort-areia.webp",
    featured: true,
    stock: 64
  },
  {
    id: "joy-rosa",
    slug: "infantil-joy-rosa",
    name: "curti Z Infantil Joy Rosa",
    category: "Infantil",
    description: "Conforto, cores alegres e segurança para os pequenos.",
    priceInCents: 3990,
    compareAtPriceInCents: 4990,
    rating: 4.7,
    reviews: 521,
    colors: ["Rosa", "Azul"],
    sizes: ["25/26", "27/28", "29/30", "31/32"],
    image: "/images/products/joy-rosa.webp",
    featured: true,
    stock: 112
  },
  {
    id: "soft-preto",
    slug: "slide-soft-preto",
    name: "curti Z Slide Soft Preto",
    category: "Slides",
    description: "Visual urbano, construção monobloco e toque macio.",
    priceInCents: 6990,
    compareAtPriceInCents: 8990,
    rating: 4.8,
    reviews: 812,
    colors: ["Preto"],
    sizes: ["35/36", "37/38", "39/40", "41/42"],
    image: "/images/products/soft-preto.webp",
    stock: 81
  },
  {
    id: "classic-preto",
    slug: "flip-flop-classic-preto",
    name: "curti Z Flip-Flop Classic Preto",
    category: "Masculino",
    description: "O essencial bem-feito, com conforto e durabilidade.",
    priceInCents: 4990,
    rating: 4.6,
    reviews: 438,
    colors: ["Preto"],
    sizes: ["37/38", "39/40", "41/42", "43/44"],
    image: "/images/products/classic-preto.webp",
    stock: 129
  },
  {
    id: "comfort-bege",
    slug: "slide-comfort-bege",
    name: "curti Z Slide Comfort Bege",
    category: "Feminino",
    description: "Tons naturais e conforto para uma rotina leve.",
    priceInCents: 7490,
    rating: 4.7,
    reviews: 307,
    colors: ["Bege"],
    sizes: ["33/34", "35/36", "37/38", "39/40"],
    image: "/images/products/comfort-bege.webp",
    stock: 55
  }
];

export const findProduct = (slug: string): Product | undefined =>
  demoProducts.find((product) => product.slug === slug);
